# Generated by Django 5.1.4 on 2025-01-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_favoritecompany_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecompany',
            name='logo',
            field=models.URLField(max_length=500),
        ),
    ]
